CREATE TABLE CLIENT(
    IDCLIENT INT AUTO_INCREMENT PRIMARY KEY,
    nomclient VARCHAR(30),
	prenomclient VARCHAR(30),
    telclient VARCHAR(30),
	adresse VARCHAR(40),
	id INT 
);

CREATE TABLE COMMANDE(
    IdCommande INT AUTO_INCREMENT PRIMARY KEY,
    DateCommande DATE,
    IDCLIENT  INT,
    FOREIGN KEY (IDCLIENT) 
    	REFERENCES CLIENT(IDCLIENT) 
    );
	
CREATE TABLE PRODUIT(
    IDPRODUIT INT AUTO_INCREMENT PRIMARY KEY,
    NomProduit VARCHAR(20),
	Quantite INT,
    Prix DOUBLE
    );

CREATE TABLE FACTURE(
    IDFACTURE INT AUTO_INCREMENT PRIMARY KEY,
    DateFacture DATE,
	Montant DOUBLE,
    IdCommande INT,
	FOREIGN KEY (IdCommande) 
    	REFERENCES COMMANDE(IdCommande) 
    );

CREATE TABLE LIVRAISON(
    IDLIVRAISON INT AUTO_INCREMENT PRIMARY KEY,
    IdCommande INT,
	DateLivraison DATE,
	FOREIGN KEY (IdCommande) 
    	REFERENCES COMMANDE(IdCommande)  
    );
	
CREATE TABLE PRODUIT_VENDUS(
    idcommande INT,
    idproduit INT,
	FOREIGN KEY (IDPRODUIT) 
    	REFERENCES PRODUIT(IDPRODUIT),
	FOREIGN KEY (IdCommande) 
    	REFERENCES COMMANDE(IdCommande) 
    );
	
CREATE TABLE ADMIN (
ID_ADMIN INT AUTO_INCREMENT PRIMARY KEY,
USER VARCHAR(20),
PASSWORD VARCHAR(20)
	);
	
INSERT INTO ADMIN values ( 1, "admin", "1234" );
	
	
